### ISSUE TITLE
create-milestone doesn't do anything if a repo is not specified

### ISSUE THREAD

**Issue by mythmon** [mozilla/pd-cli#3]
### Steps to reproduce

```shell
$ pd-cli repo create-milestone -m multi-pref-study
```

### Expected

An error is thrown since no repository was specified

### Actual

Nothing happens. No output is given, and no changes happen to any repo.

**Comment by mostlygeek** [comment]
you need to specify the <owner>/<repo-name>.  We have multiple GH accounts for projects so I didn't bake this in.
